version: '3.8'

services:
  autoblography-web:
    build: .
    ports:
      - "8000:8000"
    environment:
      # Load all variables from .env file
      - SLACK_TOKEN=${SLACK_TOKEN}
      - GOOGLE_PROJECT_ID=${GOOGLE_PROJECT_ID}
      - GOOGLE_LOCATION=${GOOGLE_LOCATION:-us-central1}
      - GOOGLE_APPLICATION_CREDENTIALS=/app/credentials/google-credentials.json
      - KAPA_API_KEY=${KAPA_API_KEY}
      - KAPA_BASE_URL=${KAPA_BASE_URL:-https://api.kapa.ai}
      - VERTEX_AI_MODEL=${VERTEX_AI_MODEL:-gemini-2.0-flash-001}
      - OUTPUT_DIR=/app/output
      - IMAGE_OUTPUT_DIR=/app/images
    volumes:
      # Mount credentials directory
      - ./credentials:/app/credentials:ro
      # Mount output directories for persistence
      - ./output:/app/output
      - ./images:/app/images
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s 